
CREATE TABLE JBT_MEM(ID VARCHAR(5),PAN_NUMBER  VARCHAR(10),ADDRESS VARCHAR(40),CITY VARCHAR(35),STATE VARCHAR(2),PINCODE integer);
CREATE TABLE VNG_MEM(NAME VARCHAR(50),DOB  VARCHAR(20),EMAIL VARCHAR(40),PHONE VARCHAR(16),ADDRESS VARCHAR(200),PINCODE integer,COUNTRY VARCHAR(20));